### ISSUE TITLE
Sprint 2: Posting an Opportunity

### ISSUE THREAD

**Issue by l1onh3art88** [victoriavo/LabRat#7]
User Stories: 1c, 1a

Summary: Let a researcher create an opportunity or event and specify the time and location. Also include basic check boxes to enable multiple preferences for a participant. For example: Male or Female. These opportunities should be posted on the homepage. 

Refer to wireframes for creating a Post Opportunity Form for GUI.

**Comment by ndenefe** [comment]
Working on it (Noah Denefe)
