### ISSUE TITLE
Sprint 3: Edit Profile Preferences 

### ISSUE THREAD

**Issue by victoriavo** [victoriavo/LabRat#9]
4i)
As a user, I wish to edit my profile preferences so that I can change what I’m interested in as well as what symptoms affect me.
Corresponding Wireframe Page: Private Profile Page
Acceptance Criteria: An edit button so a user can update their name, email, password, medical history, interest areas and research institution interests over time, save button, cancel button

**Comment by ndenefe** [comment]
Noah Denefe will take this
